import customtkinter as ctk

class Window2(ctk.CTk):
    def __init__(self):
        super().__init__()
        self.geometry("400x500В")
        self.resizable(False,False)
        self.title("New Product")
        self.configure(fg_color="grey")
        self.headerLabel = ctk.CTkLabel(self, text="New Product", text_color="black", font=("Chiron GoRound TC",20))
        self.grid1 = ctk.CTkFrame(self, width=400, height= 350, fg_color="grey")
        self.nameLabel = ctk.CTkLabel(self.grid1, text="Name of new product: ", font=("Chiron GoRound TC", 15))
        self.nameEntry = ctk.CTkEntry(self.grid1, placeholder_text="Name of the product", width=200, height= 15, font=("Chiron GoRound TC", 15))
        self.priceLabel = ctk.CTkLabel(self.grid1, text="Price of a new product: ", font=("Chiron GoRound TC", 15))
        self.priceEntry = ctk.CTkEntry(self.grid1, placeholder_text="New product`s price:", width=200, height=15, font=("Chiron GoRound TC", 15))
        self.amountLabel = ctk.CTkLabel(self.grid1, text="Amount left of a new product: ", font=("Chiron GoRound TC", 15))
        self.amountEntry = ctk.CTkEntry(self.grid1, placeholder_text="New product`s amount: ", width=200, height=15, font=("Chiron GoRound TC", 15))
        self.distributorLabel = ctk.CTkLabel(self.grid1, text="Distibutor/company producer: ", font=("Chiron GoRound TC", 15))
        self.distributorEntry = ctk.CTkEntry(self.grid1, placeholder_text="New product`s distributor/producer:", width=200, height=15, font=("Chiron GoRound TC", 15))
        self.sendButton = ctk.CTkButton(self.grid1, text="Send it to API and DB",font=("Chiron GoRound TC", 15), width=200, fg_color="red", hover_color="darkred")
        self.headerLabel.pack()
        self.grid1.pack()
        self.nameLabel.pack()
        self.nameEntry.pack()
        self.priceLabel.pack()
        self.priceEntry.pack()
        self.amountLabel.pack()
        self.amountEntry.pack()
        self.distributorLabel.pack()
        self.distributorEntry.pack()
        self.sendButton.pack()
win2 = Window2()
win2.mainloop()